config/routes.rb
Rails.application.routes.draw do
  get 'credit_card/new'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  
  devise_scope :user do
    get 'deliver_addresses', to: 'users/registrations#new_deliver_address'
    post 'deliver_addresses', to: 'users/registrations#create_deliver_address'
  end

  resources :users, only: [:index, :show, :edit] do
    member do
      get 'logout'
    end
    resources :credit_cards, only: [:new, :create, :show, :destroy]
  end

  root "items#index"
  resources :items, only: [:new, :create, :show, :destroy, :edit, :update] do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    resources :comments, only: :create do
    end
    resources :buyers, only: [:index] do
      collection do
        get 'done', to: 'buyers#done'
        post 'pay', to: 'buyers#pay'
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :credit_card, dependent: :destroy
  has_one :deliver_address, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :buy_items, class_name: 'Transaction', :foreign_key => 'buyer_id'
  has_many :sell_items, class_name: 'Transaction', :foreign_key => 'seller_id'
  
  validates :nickname, :email, :password, :family_name, :first_name, :family_name_kana, :first_name_kana, :birth_day, presence: true
  validates :family_name, :first_name, :family_name_kana, :first_name_kana, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: "全角で入力してください" }
  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: "は不正な値です" }
  validates :family_name_kana, :first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/}
  validates :password, format: { with: /\A[a-z0-9]{7,}+\z/i, message: "is too short (minimum is 7 characters)"}
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @user = User.new
  end

  # POST /resource
  def create
    @user = User.new(sign_up_params)
    unless @user.valid?
      flash.now[:alert] = @user.errors.full_messages
      render :new and return
    end
    session["devise.regist_data"] = {user: @user.attributes}
    session["devise.regist_data"][:user]["password"] = params[:user][:password]
    @deliver_address = @user.build_deliver_address
    render :new_deliver_address
  end

  def create_deliver_address
    @user = User.new(session["devise.regist_data"]["user"])
    @deliver_address = DeliverAddress.new(address_params)
    unless @deliver_address.valid?
      flash.now[:alert] = @deliver_address.errors.full_messages
      render :new_deliver_address and return
    end
    @user.build_deliver_address(@deliver_address.attributes)
    if @user.save
      session["devise.regist_data"]["user"].clear
      sign_in(:user, @user)
    else
      render :new
    end
  end

  
  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

    protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
   devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :email, :password, :family_name, :first_name, :family_name_kana, :first_name_kana, :birth_year, :birth_month, :birth_day])
  end

  def address_params
    params.require(:deliver_address).permit(:family_name, :first_name, :family_name_kana, :first_name_kana, :zip_code, :prefecture, :municipality, :building_name, :phone_number)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user_params, only: [:show]

  def index
  end

  def show
  end

  def edit
  end

  def logout
  end

  private

  def set_user_params
    @user = User.find(params[:id])
  end
  
end

app/views/users/_footer.html.haml
%aside.app-banner
  .app-banner__box
    %h2.app-banner__box__title
      だれでもかんたん、人生を変えるフリマアプリ
    %p.app-banner__box__text
      今すぐ無料ダウンロード！
    .app-banner__box__icon
      = link_to "#", class: "main-btn__apple" do
        = image_tag "material/pict/app.svg", class: "btn"
      = link_to "#", class: "main-btn__google" do
        = image_tag "material/pict/google.svg", class: "btn"
.foter
  %ul.foter__contents
    %li.content
      %h2.content__head
        FURIMAについて
      %ul.content__list
        %li.content__list__text
          = link_to "#", class: "text" do
            会社概要（運営会社）
        %li.content__list__text
          = link_to "#", class: "text" do
            プライバシーポリシー
        %li.content__list__text
          = link_to "#", class: "text" do
            FURIMA利用規約
        %li.content__list__text
          = link_to "#", class: "text" do
            ポイントに関する特約
    %li.content
      %h2.content__head
        FURIMAを見る
      %ul.content__list
        %li.content__list__text
          = link_to "#", class: "text" do
            カテゴリー一覧
        %li.content__list__text
          = link_to "#", class: "text" do
            ブランド一覧
    %li.content
      %h2.content__head
        ヘルプ＆ガイド
      %ul.content__list
        %li.content__list__text
          = link_to "#", class: "text" do
            FURIMAガイド
        %li.content__list__text
          = link_to "#", class: "text" do
            FURIMAロゴ利用ガイドライン
        %li.content__list__text
          = link_to "#", class: "text" do
            お知らせ
  .foter__logo
    = link_to "#", class: "furima-logo" do
      = image_tag "material/logo/logo-white.png", class: "img"
    %p
      © FURIMA
= link_to new_item_path, class: "display" do
  .display__btn
    %span.display__btn__text
      出品する
    = image_tag  "material/icon/icon_camera.png", class: "img"

app/views/users/_footer_image.haml
.footer__bar
  .footer__bar__middle
    .footer__bar__middle__image
 

app/views/users/_header_logo.html.haml
.header
  .header-main
    .header-main__search-bar1
      .header-main__search-bar1__logo-button
        = link_to root_path do
          = image_tag "material/logo/logo.png", class: "stylist-image1"
      .header-main__search-bar1__text
        = form_for "#" do |f|
          = f.text_field :text, class: 'header-main__search-bar1__text__form', placeholder: '何かお探しですか？'
        .header-main__search-bar1__text__box
          %label{class: "input-box__image"}
            = icon('fas', 'search', class: 'header-main__search-bar1__text__box__icon')
            %button.header-main__search-bar1__text__box__button
    .header-main__search-bar2
      .header-main__search-bar2__genre-search
        .header-main__search-bar2__genre-search__category-search
          .header-main__search-bar2__genre-search__category-search__category-image
          = link_to "/jp/category" do
            %i.fas.fa-bars
            %font{size: "2"} カテゴリーから探す
        .header-main__search-bar2__genre-search__brands-search
          .header-main__search-bar2__genre-search__brands-search__brands-image
          = link_to "/jp/brands" do
            %i.fas.fa-tag
            %font{size: "2"} ブランドから探す
      %ul.header-main__search-bar2__auth-box
        %li.header-main__search-bar2__auth-box__iine
          .iine-image
          = link_to "/jp/iine" do
            %i.far.fa-heart
            %font{size: "2"} いいね！一覧
        %li.header-main__search-bar2__auth-box__notice
          .notice-image
          = link_to "/jp/notice" do
            %i.far.fa-bell
            %font{size: "2"} お知らせ
        %li.header-main__search-bar2__auth-box__todo
          .todo-image
          = link_to "/jp/todo" do
            %i.fas.fa-check
            %font{size: "2"} やることリスト
        %li.header-main__search-bar2__auth-box__mypage
          .mypage-image
          = link_to users_path do
            %i.far.fa-smile
            %font{size: "2"} マイページ

app/views/users/_logout_main.html.haml
.logout
  .logout__container.clearfix
    .logout__content
      .logout__chapter-container
        %form.logout__single--inner
          .logout__single--content
          %button.btn-default.btn-red
            = link_to "ログアウト", destroy_user_session_path, method: :delete

app/views/users/_mypage_right.html.haml
.content-all 
  .content-all__right
    %section.content-all__right__image
      = link_to '#', class: 'content-all__right__image__profile__image__profile__name' do
        #{current_user.nickname}さんのマイページ
      .value-items 評価 8   出品数 30

  .tabs
    %input#all{checked: "checked", name: "tab_item", type: "radio"}/
    %label.tab_item{for: "all"} お知らせ
    %input#programming{name: "tab_item", type: "radio"}/
    %label.tab_item{for: "programming"} やることリスト
    #all_content.tab_content
      %li.tab_content_description
        %section.image-middle
          = image_tag "material/pict/product1.png", class: "btn",size: "48x48"
          %section.tab_content_middle 
            今ならやることキャンペーン
            %section.tab_content_middle_middle
            %i.far.fa-clock １日前
        %section.tab_content_right
          %i.fa.fa-angle-right
    #all_content.tab_content
      %li.tab_content_description
        %section.image-middle
          = image_tag "material/pict/product1.png", class: "btn",size: "48x48"
          %section.tab_content_middle 
            今だとすぐ売れるキャンペーン
            %section.tab_content_middle_middle
            %i.far.fa-clock 2日前
        %section.tab_content_right
          %i.fa.fa-angle-right
    #all_content.tab_content
      %li.tab_content_description
        %section.image-middle
          = image_tag "material/pict/product1.png", class: "btn",size: "48x48"
          %section.tab_content_middle 
            100000Pプレゼント
            %section.tab_content_middle_middle
            %i.far.fa-clock 3日前
        %section.tab_content_right
          %i.fa.fa-angle-right
    #all_content.tab_content
      %li.tab_content_description
        %section.image-middle
          = image_tag "material/pict/product1.png", class: "btn",size: "48x48"
          %section.tab_content_middle 
            ちょっとちょっと
            %section.tab_content_middle_middle
            %i.far.fa-clock 5日前
        %section.tab_content_right
          %i.fa.fa-angle-right
    #all_content.tab_content
      %li.tab_content_description
        %section.image-middle
          = image_tag "material/pict/product1.png", class: "btn",size: "48x48"
          %section.tab_content_middle 
            さすがにやばい
            %section.tab_content_middle_middle
            %i.far.fa-clock 9日前
        %section.tab_content_right
          %i.fa.fa-angle-right 
    #all_content.tab_content
      %li.tab_content_description
        %section.image-bottom
          = link_to '#', class: 'btn-icon' do
            一覧を見る
    
    #programming_content.tab_content
      .tab_content_description
      %p.c-txtsp 現在やることリストはありません   
    
  .under-tab-content
    .tab__head 
      購入した商品
    .tab_footer
      %input#tab-1{checked:"checked", name: "tab-radio", type: "radio"}/
      %label.tab-label{for:"tab-1"} 取引中
      %input#tab-2{name: "tab-radio", type: "radio"}/
      %label.tab-label{for: "tab-2"} 過去の取引
      .tab-content.tab-1-content
        -# = image_tag src="logo_gray.svg",size: "200x200", class:"all-image" 
        %p.c-txtsp 取引中の商品はありません
      .tab-content.tab-2-content
        -# = image_tag src="logo_gray.svg",size: "200x200", class:"all-image" 
        %p.c-txtsp 取引中の商品はありま--ん

app/views/users/_side_bar.html.haml
.left-content
  %menu.left-content__menu
    %ul.left-content__list
      %li
      = link_to "#", class: 'left-content__list-item' do
        マイページ
      %li
      = link_to '#', class: 'left-content__list-item' do
        お知らせ
      %li
      = link_to '#', class: 'left-content__list-item' do
        やることリスト
      %li
      = link_to '#', class: 'left-content__list-item' do
        いいね！一覧
      %li
      = link_to '#', class: 'left-content__list-item' do
        出品する
      %li
      = link_to '#', class: 'left-content__list-item' do
        出品した商品 - 出品中
      %li
      = link_to  '#', class: 'left-content__list-item' do
        出品した商品 - 取引中
      %li
      = link_to '#', class: 'left-content__list-item' do
        出品した商品 - 売却済み
      %li
      = link_to '#', class: 'left-content__list-item' do
        購入した商品 - 取引中
      %li
      = link_to '#', class: 'left-content__list-item' do
        購入した商品 - 過去の取引
      %li
      = link_to '#', class: 'left-content__list-item' do
        ニュース一覧
      %li
      = link_to '#', class: 'left-content__list-item' do
        評価一覧
      %li
      = link_to '#', class: 'left-content__list-item' do
        ガイド
      %li
      = link_to '#', class: 'left-content__list-item' do
        お問い合わせ
  %menu.left-content__middle
    メルペイ
    %ul.left-content__list
      %li
      = link_to '#', class: 'left-content__list-item' do
        売上・振込申請
      %li
      = link_to '#', class: 'left-content__list-item' do
        ポイント
  %menu.left-content__under
    設定
    %ul.left-content__list
      %li
      = link_to '#', class: 'left-content__list-item' do
        プロフィール
      %li
      = link_to '#', class: 'left-content__list-item' do
        発送先・お届け先住所変更
      %li
      - if current_user.credit_card.present?
        = link_to user_credit_card_path(user_id: current_user.id, id:[:id]), class: 'left-content__list-item' do
          支払い方法確認
      - else
        = link_to new_user_credit_card_path(user_id: current_user.id), class: 'left-content__list-item' do
          支払い方法登録
      %li
      = link_to "#", class: 'left-content__list-item' do
        メール/パスワード
      %li
      = link_to '#', class: 'left-content__list-item' do
        本人情報
      %li
      = link_to '#', class: 'left-content__list-item' do
        電話番号の確認
      %li
      = link_to logout_user_path(current_user.id), class: 'left-content__list-item' do
        ログアウト

app/views/users/index.html.haml
.wrapper
  = render 'header_logo'
  = render 'side_bar'
  = render 'mypage_right'
  = render 'footer_image'
  = render 'footer'

app/views/users/logout.html.haml
.wrapper
  = render 'header_logo'
  = render 'side_bar'
  = render 'logout_main'
  = render 'footer_image'
  = render 'footer'