config/routes.rb
Rails.application.routes.draw do
  get 'credit_card/new'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  
  devise_scope :user do
    get 'deliver_addresses', to: 'users/registrations#new_deliver_address'
    post 'deliver_addresses', to: 'users/registrations#create_deliver_address'
  end

  resources :users, only: [:index, :show, :edit] do
    member do
      get 'logout'
    end
    resources :credit_cards, only: [:new, :create, :show, :destroy]
  end

  root "items#index"
  resources :items, only: [:new, :create, :show, :destroy, :edit, :update] do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    resources :comments, only: :create do
    end
    resources :buyers, only: [:index] do
      collection do
        get 'done', to: 'buyers#done'
        post 'pay', to: 'buyers#pay'
      end
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :buyer, class_name: 'User', :foreign_key => 'buyer_id', optional: true
  belongs_to :seller, class_name: 'User', :foreign_key => 'seller_id'
  belongs_to :category
  belongs_to :brand, optional: true
  has_many :comments, dependent: :destroy
  has_many :pictures, dependent: :destroy
  accepts_nested_attributes_for :pictures, allow_destroy: true
  accepts_nested_attributes_for :brand, allow_destroy: true
  enum trading_status: { selling: 0, sold: 1 }

  validates_associated :pictures
  
  validates :name, presence: true, length: {maximum: 40}
  validates :explanation, presence: true, length: {maximum: 1000}
  validates :size, :category, :condition, :postage_payer, :shipping_origin, :days_to_ship, :trading_status, presence: true, exclusion: {in: ["選択してください"]}
  validates :price, presence: true, numericality: {greater_than: 299, less_than: 10000000}
  validates :pictures, presence: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, except: [:index, :new, :create, :get_category_children, :get_category_grandchildren]

  def index
    @items = Item.all.includes(:pictures).order('created_at DESC')
  end

  def new
    if user_signed_in?
      @item = Item.new
      @item.pictures.build
      @item.build_brand
    else
      redirect_to root_path
    end
  end

  def get_category_children
    @category_children = Category.find("#{params[:parent_id]}").children
  end

  def get_category_grandchildren
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      @item.pictures.build
      redirect_to new_item_path
    end
  end

  def show
    @user = @item.seller
    @comment = Comment.new
    @comments = @item.comments.includes(:user)
  end

  def destroy
    if @item.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def edit
    
  end

  def update
    if @item.update(item_params)
      redirect_to root_path
    else
      render :edit
    end
  end

private

  def item_params
    params.require(:item).permit(:name, :explanation, :size, :category_id, :condition, :postage_payer, :shipping_origin, :days_to_ship, :price, :trading_status, pictures_attributes: [:image, :_destroy, :id], brand_attributes: [:name]).merge(seller_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/views/items/edit.html.haml
.item__sell__header__logo
  = link_to root_path do
    = image_tag "material/logo/logo.png", class: "furima__logo"

= form_with(model: @item, local: true) do |f|
  .item__input
    .item__sell__form1
      .form__frame
        .item__picture
          %label.item__picture__label
            出品画像
          %span.required
            必須
          %p.picture__upper__limit
            最大５枚までアップロードできます
        .files__content__edit
          #previews__edit
            - @item.pictures.each_with_index do |picture, i|
              #preview__edit
                = image_tag picture.image.url, data: {index: i}, width:"100", height:"100"
                .js-remove{"data-index": i}
                  削除
          %label.change__form-id
            #files__content__form__edit
              = icon("fa", "camera")
              %p.how__to__upload
                クリックしてファイルをアップロード
              = f.fields_for :pictures, @item.pictures do |picture|
                .js-file_group_edit{ "data-index": "#{ picture.index }"}
                  = picture.file_field :image, class: 'file__upload__edit'
                - if @item.persisted?
                  = picture.check_box :_destroy, data:{ index: picture.index }, class: 'hidden-destroy'
              - if @item.persisted?
                .js-file_group_edit{ "data-index": "#{ @item.pictures.count }"}
                  = file_field_tag :image, name: "item[pictures_attributes][#{@item.pictures.count }][image]", id: "item_pictures_attributes_#{@item.pictures.count }_image", class: 'file__upload__edit'
    %hr.style__line

    .item__sell__form2
      .form__frame
        .item__name
          %label.item__name__label 
            商品名
          %span.required
            必須
        = f.text_field :name, id: 'name', size: 40, placeholder: "40文字まで"
        .item__explanation
          %label.item__explanation__label
            商品説明
          %span.required
            必須
        = f.text_area :explanation, id: 'explanation', size: "40x25", placeholder: "商品の説明（必須 1,000文字以内）\n（色、素材、重さ、定価、注意点など）\n\n例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"
    %hr.style__line

    .item__sell__form3
      .form__frame
        .item__detail
          商品の詳細
        .item__category
          %label.item__category__label
            カテゴリー
          %span.required
            必須
          = f.collection_select :category_id, Category.where(ancestry: nil).each, :id, :name, { selected: @item.category.root_id }, {class: 'listing-select-wrapper__box--select', id: 'parent_category'}
          - if @item.persisted?
            = f.collection_select :category_id, @item.category.root.children, :id, :name, { selected: @item.category.parent_id }, {class: 'listing-select-wrapper__box--select', id: 'child_category'}
            = f.collection_select :category_id, @item.category.root.indirects, :id, :name, { selected: @item.category_id }, {class: 'listing-select-wrapper__box--select', id: 'grandchild_category'}

        .item__size
          %label.item__size__label
            サイズ
          %span.required
            必須
        = f.collection_select :size, Fit.all, :name, :name, { include_blank: "選択してください", selected: @item.size }, {id: 'size'}
        .item__brand
          %label.item__brand__label
            ブランド
          %span.no-required
            任意
        = f.fields_for :brand do |brand|
          = brand.text_field :name, id: 'brand', placeholder: "例）シャネル"
        .item__condition
          %label.item__condition__label
            商品の状態
          %span.required
            必須
        = f.collection_select :condition, Quality.all, :name, :name, { include_blank: "選択してください", selected: @item.condition }, {id: 'condition'}
    %hr.style__line

    .item__sell__form4
      .form__frame
        .about__shipping
          配送について
        .item__postage__payer
          %label.item__postage__payer__label
            配送料の負担
          %span.required
            必須
        = f.collection_select :postage_payer, Burden.all, :name, :name, { include_blank: "選択してください", selected: @item.postage_payer }, {id:'postage__payer'}
        .item__shipping__origin
          %label.item__shipping__origin__label
            発送元の地域
          %span.required
            必須
        = f.collection_select :shipping_origin, Prefecture.all, :name, :name, { include_blank: "選択してください", selected: @item.shipping_origin }, {id: 'shipping__origin'}
        .item__days__to__ship
          %label.item__days__to__ship__label
            発送までの日数
          %span.required
            必須
        = f.collection_select :days_to_ship, Days.all, :name, :name, { include_blank: "選択してください", selected: @item.days_to_ship }, {id: 'days__to__ship'}
    %hr.style__line

    .item__sell__form5
      .form__frame
        .about__price
          価格（￥300〜9,999,999）
        .item__price
          %label.item__price__label
            販売価格
          %span.required
            必須
          %span.yen
            ¥
          = f.number_field :price, id: 'price', min: 300, max: 9999999, placeholder: '0'
        .sales__commission
          .sales__commission__label
            販売手数料（10％）
          .sales__commission__value
            ー
        %hr.style__line
        .sales__profit
          .sales__profit__label
            販売利益
          .sales__profit__value
            ー
        .item__submit__form
          = f.submit '編集する', id: 'item__submit'
          %button{type: 'submit', id: 'item__submit__draft'}
            下書きに保存
          = link_to root_path, class: "return__link" do
            もどる
        .precautions
          禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。
.item__sell__footer
  %ul
    %li
      プライバシーポリシー
    %li
      フリマ利用規約
    %li
      特定商取引に関する表記
  .item__sell__footer__logo
    = link_to root_path do
      = image_tag "material/logo/logo-white.png", class: "furima__white__logo"

app/views/items/index.html.haml
.header
  .header__inner
    .wrapper
      %h1.wrapper__logo
        = link_to root_path, class: "wrapper__logo__furima" do
          = image_tag "material/logo/logo.png", class: "stylist-image1"
      .wrapper__search-box
        %form.wrapper__search-box__form
          %input{type: 'text', class: 'form-text', placeholder: "キーワードから探す"}
          %button{type: 'submit', class: 'form-submit'}
            .form-submit__logo
              = image_tag "material/icon/icon-search 1.png", class: "stylist-image2"
    .navigation
      %ul.list-left
        %li.list-left__item
          = link_to "#", class: "list-left__item__category" do
            カテゴリー
        %li.list-left__item__btn
          = link_to "#", class: "burand" do
            ブランド
      %ul.list-right
        - if user_signed_in?
          %li.list-right__item
            = link_to logout_user_path(current_user.id), class: "list-right__item__btn" do
              ログアウト
          %li.list-right__item
            = link_to users_path, class: "list-right__item__btn" do
              マイページ
        - else
          %li.list-right__item
            = link_to new_user_session_path, class: "list-right__item__btn" do
              ログイン
          %li.list-right__item
            = link_to new_user_registration_path, class: "list-right__item__btn" do
              新規会員登録
.main
  %section.main__image
    .main__image__contents
      %h2.title 
        %br
        人生を変えるフリマアプリ
      %p.text
        FURIMAはだれでもかんたんに出品・購入できる
        %br 
        フリマアプリです
      .main-btn
        = link_to "#", class: "main-btn__apple" do
          = image_tag "material/pict/app.svg", class: "btn"
        = link_to "#", class: "main-btn__google" do
          = image_tag "material/pict/google.svg", class: "btn"
  %section.top-explanation
    %h2.top-explanation__text
      FURIMAが選ばれる3つの理由
    %ul.lists 
      %li.list
        .list__picture
          %span.number
            1
          = image_tag "material/pict/pict-reason-01.jpg", class: "img"
        %h3.list__text
          %span
            3分
          ですぐに出品
        %p.list__explanation
          スマホで入力するだけで簡単に出品できる！
      %li.list
        .list__picture
          %span.number
            2
          = image_tag "material/pict/pict-reason-02.jpg", class: "img"
        %h3.list__text
          %span
            シンプル
          で使いやすい
        %p.list__explanation
          めんどくさい入力は必要なく、検索も購入もスムーズ！
      %li.list
        .list__picture
          %span.number
            3
          = image_tag "material/pict/pict-reason-03.jpg", class: "img"
        %h3.list__text
          手数料
          %span
            業界最安
        %p.list__explanation
          最大3%でお得に出品&購入！
  %section.middle-image
    .middle-image__contents
      %h2.middle-image__contents__title
        会員数日本一位
      %p.middle-image__contents__text
        FURIMAは、フリマアプリで最も人気。
        %br
        出品・購入回数も業界最多です！
        %br
        ほしかったあの商品に出会えるかもしれません。
      .middle-image__contents__btn
        = link_to "#", class: "middle-image__contents__btn__apple" do
          = image_tag "material/pict/app.svg", class: "btn"
        = link_to "#", class: "main-btn__google" do
          = image_tag "material/pict/google.svg", class: "btn"
  %section.middle-explanation
    %h2.middle-explanation__text
      FURIMAの特徴
    %ul.lists 
      %li.list
        .list__picture
          = image_tag "material/icon/icon-01.png", class: "img"
        %h3.list__text
          簡単に売り買いできる
        %p.list__explanation
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      %li.list
        .list__picture
          = image_tag "material/icon/icon-03.png", class: "img"
        %h3.list__text
          売上金は即日振込みに対応
        %p.list__explanation
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
      %li.list
        .list__picture
          = image_tag "material/icon/icon-04.png", class: "img"
        %h3.list__text
          様々な支払いに対応
        %p.list__explanation
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
  %section.pickup
    %h2.pickup__text
      ピックアップカテゴリー
    .pickup__box
      .pickup__box__text
        = link_to "#", class: "pickup__box__text__link" do
          %h3.title
            新規投稿商品
      .pickup__box__lists
        - @items.each do |item|
          -if item.buyer_id.present?
            .list
              = link_to root_path, class: "list__link" do
                %figure.list__link__image
                  = image_tag item.pictures[0].image.to_s, size: '220x150'
                .list__link__body
                  %h3.name
                    = item.name
                  .detai
                    %ul.detai__lists
                      %li
                        = item.price
                      %li
                        %i.fa.fa-star
                        0
                    %p
                      (税込) 
              .items-box_photo__sold
                .items-box_photo__sold__inner
                  SOLD
          -else
            .list
              = link_to item_path(item.id), class: "list__link" do
                %figure.list__link__image
                  = image_tag item.pictures[0].image.to_s, size: '220x150'
                .list__link__body
                  %h3.name
                    = item.name
                  .detai
                    %ul.detai__lists
                      %li
                        = item.price
                      %li
                        %i.fa.fa-star
                        0
                    %p
                      (税込)

%aside.app-banner
  .app-banner__box
    %h2.app-banner__box__title
      だれでもかんたん、人生を変えるフリマアプリ
    %p.app-banner__box__text
      今すぐ無料ダウンロード！
    .app-banner__box__icon
      = link_to "#", class: "main-btn__apple" do
        = image_tag "material/pict/app.svg", class: "btn"
      = link_to "#", class: "main-btn__google" do
        = image_tag "material/pict/google.svg", class: "btn"
.foter
  %ul.foter__contents
    %li.content
      %h2.content__head
        FURIMAについて
      %ul.content__list
        %li.content__list__text
          = link_to "#", class: "text" do
            会社概要（運営会社）
        %li.content__list__text
          = link_to "#", class: "text" do
            プライバシーポリシー
        %li.content__list__text
          = link_to "#", class: "text" do
            FURIMA利用規約
        %li.content__list__text
          = link_to "#", class: "text" do
            ポイントに関する特約
    %li.content
      %h2.content__head
        FURIMAを見る
      %ul.content__list
        %li.content__list__text
          = link_to "#", class: "text" do
            カテゴリー一覧
        %li.content__list__text
          = link_to "#", class: "text" do
            ブランド一覧
    %li.content
      %h2.content__head
        ヘルプ＆ガイド
      %ul.content__list
        %li.content__list__text
          = link_to "#", class: "text" do
            FURIMAガイド
        %li.content__list__text
          = link_to "#", class: "text" do
            FURIMAロゴ利用ガイドライン
        %li.content__list__text
          = link_to "#", class: "text" do
            お知らせ
  .foter__logo
    = link_to "#", class: "furima-logo" do
      = image_tag "material/logo/logo-white.png", class: "img"
    %p
      © FURIMA
= link_to new_item_path, class: "display" do
  .display__btn
    %span.display__btn__text
      出品する
    = image_tag  "material/icon/icon_camera.png", class: "img"

app/views/items/show.html.haml
.header
  .header__inner
    .wrapper
      %h1.wrapper__logo
        = link_to root_path, class: "wrapper__logo__furima" do
          = image_tag "material/logo/logo.png", class: "stylist-image1"
      .wrapper__search-box
        %form.wrapper__search-box__form
          %input{type: 'text', class: 'form-text', placeholder: "キーワードから探す"}
          %button{type: 'submit', class: 'form-submit'}
            .form-submit__logo
              = image_tag "material/icon/icon-search 1.png", class: "stylist-image2"
    .navigation
      %ul.list-left
        %li.list-left__item
          = link_to "#", class: "list-left__item__category" do
            カテゴリー
        %li.list-left__item__btn
          = link_to "#", class: "burand" do
            ブランド
      %ul.list-right
        - if user_signed_in?
          %li.list-right__item
            = link_to destroy_user_session_path, method: :delete, class: "list-right__item__btn" do
              ログアウト
          %li.list-right__item
            = link_to "#", class: "list-right__item__btn" do
              マイページ
        - else
          %li.list-right__item
            = link_to new_user_session_path, class: "list-right__item__btn" do
              ログイン
          %li.list-right__item
            = link_to new_user_registration_path, class: "list-right__item__btn" do
              新規会員登録
%nav.category
  %ul.category__ul
    - if !@item.category.parent_id
      %li.category__ul__li
        = link_to "#", class: "btn" do
          FURIMA
      %li.category__ul__li
        = link_to "#", class: "btn" do
          = @item.category.name
      %li.category__ul__li
        = icon('fa', 'angle-right')
      %li.category__ul__li
        = link_to "#", class: "btn-bold" do
          = @item.name
    - elsif !@item.category.parent.parent_id
      %li.category__ul__li
        = link_to "#", class: "btn" do
          FURIMA
      %li.category__ul__li
        = icon('fa', 'angle-right')
      %li.category__ul__li
        = link_to "#", class: "btn" do
          = @item.category.parent.name
      %li.category__ul__li
        = icon('fa', 'angle-right')
      %li.category__ul__li
        = link_to "#", class: "btn" do
          = @item.category.name
      %li.category__ul__li
        = icon('fa', 'angle-right')
      %li.category__ul__li
        = link_to "#", class: "btn-bold" do
          = @item.name
    - else
      %li.category__ul__li
        = link_to "#", class: "btn" do
          FURIMA
      %li.category__ul__li
        = icon('fa', 'angle-right')
      %li.category__ul__li
        = link_to "#", class: "btn" do
          = @item.category.parent.parent.name
      %li.category__ul__li
        = icon('fa', 'angle-right')
      %li.category__ul__li
        = link_to "#", class: "btn" do
          = @item.category.parent.name
      %li.category__ul__li
        = icon('fa', 'angle-right')
      %li.category__ul__li
        = link_to "#", class: "btn" do
          = @item.category.name
      %li.category__ul__li
        = icon('fa', 'angle-right')
      %li.category__ul__li
        = link_to "#", class: "btn-bold" do
          = @item.name
.main
  .main__show
    .main__show__content
      .item
        .item__box
          %h2.item__box__name
            = @item.name
          .item__box__body
            %ul.image
              - objects = @item.pictures
              - objects.each do |object|
                %li.list
                  = image_tag object.image.url, class: "list__size"
          .item__box__price
            %span.price
              = @item.price
            .detail
              %span
                (税込)
              %span
                送料込み
          .item__box__detail
            = simple_format @item.explanation
          .item__box__table
            %table.table
              %tbody.tbody
                %tr.tr
                  %th.th
                    出品者
                  %td.td
                    = @user.nickname
                %tr.tr
                  %th.th
                    カテゴリ
                  %td.td
                    - if !@item.category.parent_id
                      = link_to "#", class: "td__color" do
                        .item-detail-table-sub
                          = @item.category.name
                    - elsif !@item.category.parent.parent_id
                      = link_to "#", class: "td__color" do
                        .item-detail-table-sub
                          = @item.category.parent.name
                      = link_to "#", class: "td__color" do
                        .item-detail-table-sub__sub
                          = @item.category.name
                    - else
                      = link_to "#", class: "td__color" do
                        .item-detail-table-sub
                          = @item.category.parent.parent.name
                      = link_to "#", class: "td__color" do
                        .item-detail-table-sub__sub
                          = @item.category.parent.name
                      = link_to "#", class: "td__color" do
                        .item-detail-table-sub__sub__sub
                          = @item.category.name
                %tr.tr
                  %th.th
                    ブランド
                  %td.td
                    = @item.brand.name
                %tr.tr
                  %th.th
                    商品のサイズ
                  %td.td
                    = @item.size
                %tr.tr
                  %th.th
                    商品の状態
                  %td.td
                    = @item.condition
                %tr.tr
                  %th.th
                    配送料の負担
                  %td.td
                    = @item.postage_payer
                %tr.tr
                  %th.th
                    発送元の地域
                  %td.td
                    = link_to "#", class: "td__color" do
                      = @item.shipping_origin
                %tr.tr
                  %th.th
                    発送日の目安
                  %td.td
                    = @item.days_to_ship
          - if user_signed_in? && current_user.id == @item.seller_id
            %li.item__box__btn
              %ul.edit
                = link_to edit_item_path, class: "edit" do
                  編集
              %ul.delete
                = link_to item_path(@item.id), method: :delete, class: "delete" do
                  削除
          - elsif user_signed_in?
            .item__box__buy
              = link_to item_buyers_path(@item), class: "buy-color" do
                購入画面に進む
          - else
            .item__box__buy
              = link_to new_user_session_path, class: "buy-color" do
                新規登録画面に進む
            .item__box__option
              %ul.like
                %li.like__btn
                  = icon('fa', 'star')
                  お気に入り 0
              %ul.report
                %li.report__btn
                  = link_to "#", class: "report__btn__text" do
                    = icon('fa', 'flag')
                    不適切な商品の通報
        .item__box__comment
          - if current_user 
            = form_with(model: [@item, @comment], local: true) do |form|
              = form.text_area :text, rows: "2", class: 'form__text'
              %p.form__note
                相手のことを考え丁寧なコメントを心がけましょう。
                %br
                不快な言葉遣いなどは利用制限や退会処分となることがあります。
                %br
              = button_tag type: 'submit', class: 'form__button' do
                = icon('fa', 'comment')
                コメントする
          - else 
            %strong
              %p
                ※※※ コメントの投稿には新規登録/ログインが必要です ※※※
          .comments
            %h4
              <コメント一覧>
            - if @comments 
              - @comments.each do |comment|
                %p
                  %strong
                    = comment.user.nickname
                  = comment.text
      %ul.main__show__links
        %li.link
          = link_to "#", class: "link__btn" do
            = icon('fa', 'angle-left')
            %span
            前の商品
        %li.link-right
          = link_to "#", class: "link__btn" do
            %span
              後ろの商品
            = icon('fa', 'angle-right')
      .main__show__relation
        = link_to "#", class: "btn" do
          ベビー・キッズをもっと見る
%aside.app-banner
  .app-banner__box
    %h2.app-banner__box__title
      だれでもかんたん、人生を変えるフリマアプリ
    %p.app-banner__box__text
      今すぐ無料ダウンロード！
    .app-banner__box__icon
      = link_to "#", class: "main-btn__apple" do
        = image_tag "material/pict/app.svg", class: "btn"
      = link_to "#", class: "main-btn__google" do
        = image_tag "material/pict/google.svg", class: "btn"
.foter
  %ul.foter__contents
    %li.content
      %h2.content__head
        FURIMAについて
      %ul.content__list
        %li.content__list__text
          = link_to "#", class: "text" do
            会社概要（運営会社）
        %li.content__list__text
          = link_to "#", class: "text" do
            プライバシーポリシー
        %li.content__list__text
          = link_to "#", class: "text" do
            FURIMA利用規約
        %li.content__list__text
          = link_to "#", class: "text" do
            ポイントに関する特約
    %li.content
      %h2.content__head
        FURIMAを見る
      %ul.content__list
        %li.content__list__text
          = link_to "#", class: "text" do
            カテゴリー一覧
        %li.content__list__text
          = link_to "#", class: "text" do
            ブランド一覧
    %li.content
      %h2.content__head
        ヘルプ＆ガイド
      %ul.content__list
        %li.content__list__text
          = link_to "#", class: "text" do
            FURIMAガイド
        %li.content__list__text
          = link_to "#", class: "text" do
            FURIMAロゴ利用ガイドライン
        %li.content__list__text
          = link_to "#", class: "text" do
            お知らせ

  .foter__logo
    = link_to "#", class: "furima-logo" do
      = image_tag "material/logo/logo-white.png", class: "img"
    %p
      © FURIMA
= link_to new_item_path, class: "display" do
  .display__btn
    %span.display__btn__text
      出品する
    = image_tag "material/icon/icon_camera.png", class: "img"